### ISSUE TITLE
Darwin Core Hour Notes - Google Doc getting large - tracking next steps challenging

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#31]
Our [Google Doc for Darwin Core Hour note-taking](https://docs.google.com/document/d/1S_MzK5qhZVxGRNYDp6aslA2jZ-zo6m-KufLBqvc9IFY/edit?usp=sharing) AND for our after-event meetings is getting rather large and perhaps a bit unwieldy. Suggestions please for improving this process?

Some ideas:

- for 2018 we start a new Google Doc
- create a separate wiki page for all upcoming webinar ideas / possible presenters?
-- otherwise, one has to re-read through the huge Google Doc looking for these ideas again-and-again

Thoughts for how to streamline this process to prevent losing ideas?

**Comment by tucotuco** [comment]
I think ideas could come out as issues, which are made for tracking. It
might not be a bad idea to have one doc per year. The benefit of having
notes for multiple webinars is the searching, in case one can't remember
when it came from.

**Comment by debpaul** [comment]
Works for me @tucotuco. To Do's 
- [x] Create new Google Doc for our 2018 Webinars
https://docs.google.com/document/d/1rL6KwWSs8SiNmBjkXDeJgOI2QxqIFBE0X9p9NaiSSYM/edit?usp=sharing
- [x] Link the 2017 and 2018 google docs to each other
- [ ] Link these Google Docs in this / and tdwg-qa repo - where?
- [ ] We may add an "idea" tag to issues? (b/c they're not necessarily a webinar)
- [ ] Do we need to create an Archive copy (read-only version) of the notes (to safeguard?)
And +1 to the need to search - b/c otherwise often impossible to remember source.
