### ISSUE TITLE
Checklist for Webinar: The problem of time, scheduled for April 24th 2018

### ISSUE THREAD

**Issue by debpaul** [VertNet/dwc-qa-manage#33]
Checklist for webinar The Problem of Time: Dealing with Paleontological and Zooarchaeological Specimens in Darwin Core, scheduled for April 24, 2018

To do items include:

- [x] Date and time
- [x] Title
- [x] Abstract
- [x] Presenter/s
- [x] Relevant links and reading materials
- [x] Moderator/s
- [x] post iDigBio Calendar Announcement
- [x] add tdwg/dwc-qa/wiki/Webinars entry, link iDigBio Calendar Announcement
- [x] Schedule webinar (at https://idigbio.adobeconnect.com/
- [x] Schedule sound/screen check (at https://idigbio.adobeconnect.com/)
- [x] Request survey content from presenters
- [x] Send presenters feedback request to Shari and get survey link from Shari at iDigBio
- [x] Generate tinyURL for survey
- [x] Written [intro](https://github.com/VertNet/dwc-qa-manage/wiki/Webinar-Preparation-Checklist#example-webinar-introduction-script) to webinar
- [x] Prepare AdobeConnect environment
- [x] Send emails advertising DwC Hour one week prior
- [x] Send emails advertising DwC Hour one day prior
- [x] Post webinar - add adobe connect link to tdwg/dwc-qa/wiki/Webinars entry
- [x] Post webinar - render vimeo mp4 recording from adobe connect recording
- [x] Post webinar - add vimeo link to tdwg/dwc-qa/wiki/Webinars entry
- [x] Post webinar - add link to slides to tdwg/dwc-qa/wiki/Webinars entry
- [x] Post webinar - add link to Adobe Connect and MP4 links to iDigBio announcement
- [x] Post webinar - put post-webinar survey results in folder (folder to be created)
- [x] Post webinar - meet and review webinar conversations for next steps, new webinars, etc.
- [x] Close ticket when done

**Comment by ekrimmel** [comment]
team can review webinar conversations during July workday
